version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: aven-test-password
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
