version: 2
jobs:
  test:
    machine:
      enable: true
    image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-utils
            sudo apt-get install -y libssl-dev build-essential curl
            sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
            sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo  apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo  tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install -y nodejs yarn build-essential apt-transport-https   ca-certificates    curl   gnupg2 software-properties-common
            sudo git checkout $CIRCLE_BRANCH
            sudo yarn install
            sudo yarn test

workflows:
  version: 2
  test:
    jobs:
      - test