version: 2
jobs:
  test:
    machine:
      enable: true
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
    image: circleci/node:8-browsers

    working_directory: ~/circleci-aven

    steps:
      - checkout
      - restore_cache:
          keys:
          - aven-yarn-{{ checksum "yarn.lock" }}
          - aven-yarn-

      - save_cache:
          key: aven-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: 'Build'
          command: yarn build
      
      - run:
          name: 'Test'
          command: yarn test'


workflows:
  version: 2
  build_and_test:
    jobs:
      - test